=== CRC-IRAN/naaccr-xml/src/test/resources/roger/naaccr7.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://naaccr.org/naaccrfile" targetNamespace="http://naaccr.org/naaccrfile" >

<xsd:element name="NAACCRDataExchange">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:Dictionary" minOccurs="0" maxOccurs="1" />
			<xsd:element ref="tns:Patient" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="tns:CancerRecord" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="extractID" use="optional" />
		<xsd:attribute name="NAACCRVersion" use="required" />
		<xsd:attribute name="xsdVersion" use="optional" fixed="1.0" />
		<xsd:attribute name="datePrepared" use="required" type="xsd:dateTime" />
		<xsd:attribute name="sender" use="required" />
		<xsd:attribute name="senderCode" use="optional" />
		<xsd:attribute name="description" use="optional" />
		<xsd:attribute name="geography" use="optional" />
		<xsd:attribute name="dateFrom" use="optional" type="xsd:date" />
		<xsd:attribute name="dateTo" use="optional" type="xsd:date" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="Patient">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:Item" minOccurs="0" maxOccurs="unbounded" />
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="tns:Tumor" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="Tumor">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:Item" minOccurs="0" maxOccurs="unbounded" />
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="CancerRecord">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:Item" minOccurs="0" maxOccurs="unbounded" />
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="documentID" use="optional" type="xsd:string" />
		<xsd:attribute name="timeStamp" use="optional" type="xsd:dateTime" />
		<xsd:attribute name="isVoid" use="optional" type="xsd:boolean" default="false" />
		<xsd:attribute name="voidBy" use="optional" />
		<xsd:attribute name="voidDate" use="optional" type="xsd:date" />
		<xsd:attribute name="voidReason" use="optional" />
	</xsd:complexType>
</xsd:element>

<xsd:complexType name="itemType" >
	<xsd:simpleContent>
		<xsd:extension base="xsd:string" >
			<xsd:attribute name="itemNo" type="xsd:integer" use="optional" />
			<xsd:attribute name="itemName" use="optional" type="xsd:IDREF" />
			<xsd:attribute name="isDeprecated" use="optional" type="xsd:boolean" default="false" />
			<xsd:attribute name="isMissing" use="optional" type="xsd:boolean" default="false" />
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:element name="Item" type="tns:itemType" />

<xsd:element name="Dictionary">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:ItemDefs" />
		</xsd:sequence>
		<xsd:attribute name="dictionaryVersion" use="optional" />
		<xsd:attribute name="releaseDate" use="optional" />
		<xsd:attribute name="description" use="optional" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="ItemDefs">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:ItemDef" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:simpleType name="datatypeType">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="code" />
		<xsd:enumeration value="codeWithBlank" />
		<xsd:enumeration value="alpha" />
		<xsd:enumeration value="alphaWithBlank" />
		<xsd:enumeration value="date" />
		<xsd:enumeration value="string" />
		<xsd:enumeration value="stringInitialBlankOK" />
		<xsd:enumeration value="integer" />
		<xsd:enumeration value="integerLeftZeroPad" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:element name="ItemDef">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="tns:ValidValue" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="itemName" use="required" type="xsd:ID" />
		<xsd:attribute name="itemNo" use="required" type="xsd:integer" />
		<xsd:attribute name="datatype" use="required" type="tns:datatypeType" />
		<xsd:attribute name="parentElement" use="required" type="xsd:string" />
		<xsd:attribute name="longName" use="optional" type="xsd:string" />
		<xsd:attribute name="section" use="optional" type="xsd:string" />
		<xsd:attribute name="fixedStart" use="optional" type="xsd:integer" />
		<xsd:attribute name="itemLength" use="optional" type="xsd:integer" />
		<xsd:attribute name="retiredVersion" use="optional" type="xsd:string" />
		<xsd:attribute name="sourceOfStandard" use="optional" type="xsd:string" />
		<xsd:attribute name="recordTypes" use="optional" type="xsd:string" />
		<xsd:attribute name="regex" use="optional" type="xsd:string" />
		<xsd:attribute name="shadow" use="optional" type="xsd:boolean" default="false" />
	</xsd:complexType>
</xsd:element>

<xsd:element name="ValidValue" >
	<xsd:complexType>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="code" use="required" type="xsd:string" />
				<xsd:attribute name="description" use="optional" />
				<xsd:attribute name="isMissing" use="optional" type="xsd:boolean" default="false" />
			</xsd:extension>	
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== CRC-IRAN/naaccr-xml/src/test/resources/roger/naaccr7dict.xml
<?xml version="1.0"?>
<NAACCRDataExchange xmlns="http://naaccr.org/naaccrfile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://naaccr.org/naaccrfile/naaccr7.xsd"
NAACCRVersion="140" XSDVersion="1.0" description="NAACCR v14 base dictionary" datePrepared="2014-12-18T09:06:25" >
	<Dictionary releaseDate="2014-12-18T09:06:25" >
		<ItemDefs>
			<ItemDef itemNo="10" itemName="RecType" longName="Record Type" 
				itemLength="1" fixedStart="1" section="Record ID" recordTypes="I,C,A,M" 
				regex="^[ICAM]$" parentElement="CancerRecord" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="20" itemName="PatientID" longName="Patient ID Number" 
				itemLength="8" fixedStart="42" section="Record ID" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="21" itemName="PTSysIDHosp" longName="Patient System ID-Hosp" 
				itemLength="8" fixedStart="50" section="Record ID" recordTypes="I,C,A,M" 
				datatype="integer" parentElement="CancerRecord" sourceOfStandard="NAACCR11" />
			<ItemDef itemNo="30" itemName="RegType" longName="Registry Type" 
				itemLength="1" fixedStart="2" section="Record ID" recordTypes="I,C,A,M" 
				datatype="code" parentElement="CancerRecord" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="40" itemName="RegistryID" longName="Registry ID" 
				itemLength="10" fixedStart="30" section="Record ID" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="CancerRecord" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="45" itemName="NPIRegID" longName="NPI--Registry ID" 
				itemLength="10" fixedStart="20" section="Record ID" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="CancerRecord" sourceOfStandard="NAACCR111" />
			<ItemDef itemNo="50" itemName="NAACCRRecVer" longName="NAACCR Record Version" 
				itemLength="3" fixedStart="17" section="Record ID" recordTypes="I,C,A,M" 
				datatype="code" parentElement="CancerRecord" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="60" itemName="TumRecNum" longName="Tumor Record Number" 
				itemLength="2" fixedStart="40" section="Record ID" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="70" itemName="DxCity" longName="Addr at DX--City" 
				itemLength="50" fixedStart="95" section="Demographic" recordTypes="I,C,A,M" 
				datatype="string" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="80" itemName="DxState" longName="Addr at DX--State" 
				itemLength="2" fixedStart="145" section="Demographic" recordTypes="I,C,A,M" 
				datatype="alpha" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="90" itemName="DxCounty" longName="County at DX" 
				itemLength="3" fixedStart="156" section="Demographic" recordTypes="I,C,A,M" 
				datatype="alpha" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="100" itemName="DxPostalZip" longName="Addr at DX--Postal Code" 
				itemLength="9" fixedStart="147" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="102" itemName="DxCountry" longName="Addr at DX--Country" 
				itemLength="3" fixedStart="436" section="Demographic" recordTypes="I,C,A,M" 
				datatype="alpha" parentElement="Tumor" sourceOfStandard="NAACCR13" />
			<ItemDef itemNo="110" itemName="CenTract708090" longName="Census Tract 1970/80/90" 
				itemLength="6" fixedStart="159" section="Demographic" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="120" itemName="CenCodSys708090" longName="Census Cod Sys 1970/80/90" 
				itemLength="1" fixedStart="166" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="130" itemName="CenTract2000" longName="Census Tract 2000" 
				itemLength="6" fixedStart="168" section="Demographic" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="135" itemName="CenTract2010" longName="Census Tract 2010" 
				itemLength="6" fixedStart="428" section="Demographic" recordTypes="I,C,A,M" 
				datatype="integerWithZero" parentElement="Tumor" sourceOfStandard="NAACCR121" />
			<ItemDef itemNo="145" itemName="PovertyInd" longName="Census Tr Poverty Indictr" 
				itemLength="1" fixedStart="463" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR13" />
			<ItemDef itemNo="150" itemName="Marital" longName="Marital Status at DX" 
				itemLength="1" fixedStart="176" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="160" itemName="Race1" longName="Race 1" 
				itemLength="2" fixedStart="177" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="161" itemName="Race2" longName="Race 2" 
				itemLength="2" fixedStart="179" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR8" />
			<ItemDef itemNo="162" itemName="Race3" longName="Race 3" 
				itemLength="2" fixedStart="181" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR8" />
			<ItemDef itemNo="163" itemName="Race4" longName="Race 4" 
				itemLength="2" fixedStart="183" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR8" />
			<ItemDef itemNo="164" itemName="Race5" longName="Race 5" 
				itemLength="2" fixedStart="185" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR8" />
			<ItemDef itemNo="170" itemName="RaceCodSysCur" longName="Race Coding Sys--Current" 
				itemLength="1" fixedStart="187" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="180" itemName="RaceCodSysOrg" longName="Race Coding Sys--Original" 
				itemLength="1" fixedStart="188" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="190" itemName="Hispanic" longName="Spanish/Hispanic Origin" 
				itemLength="1" fixedStart="189" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="191" itemName="NHIA" longName="NHIA Derived Hisp Origin" 
				itemLength="1" fixedStart="418" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR102" />
			<ItemDef itemNo="192" itemName="IHSLink" longName="IHS Link" 
				itemLength="1" fixedStart="421" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR11" />
			<ItemDef itemNo="193" itemName="RaceNAPIIA" longName="Race--NAPIIA(derived API)" 
				itemLength="2" fixedStart="419" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR113" />
			<ItemDef itemNo="200" itemName="CompEthn" longName="Computed Ethnicity" 
				itemLength="1" fixedStart="190" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="210" itemName="CompEthnSrc" longName="Computed Ethnicity Source" 
				itemLength="1" fixedStart="191" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="220" itemName="Sex" 
				itemLength="1" fixedStart="192" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="230" itemName="AgeDx" longName="Age at Diagnosis" 
				itemLength="3" fixedStart="193" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="240" itemName="BirthDate" longName="Date of Birth" 
				itemLength="8" fixedStart="196" section="Demographic" recordTypes="I,C,A,M" 
				datatype="date" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="241" itemName="BirthDateFlag" longName="Date of Birth Flag" 
				itemLength="2" fixedStart="204" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR12" />
			<ItemDef itemNo="250" itemName="BPCode" longName="Birthplace" 
				itemLength="3" fixedStart="206" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Patient" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="252" itemName="BPState" longName="Birthplace--State" 
				itemLength="2" fixedStart="442" section="Demographic" recordTypes="I,C,A,M" 
				datatype="alpha" parentElement="Patient" sourceOfStandard="NAACCR13" />
			<ItemDef itemNo="254" itemName="BPCountry" longName="Birthplace--Country" 
				itemLength="3" fixedStart="444" section="Demographic" recordTypes="I,C,A,M" 
				datatype="alpha" parentElement="Patient" sourceOfStandard="NAACCR13" />
			<ItemDef itemNo="270" itemName="OccCen" longName="Census Occ Code 1970-2000" 
				itemLength="3" fixedStart="209" section="Demographic" recordTypes="I,C,A,M" 
				datatype="code" parentElement="Tumor" sourceOfStandard="NAACCR51" />
			<ItemDef itemNo="272" itemName="IndCen2010" longName="Census Ind Code 2010" 
				itemLength="4" fixedStart="455" section="Demographic" recordTypes="I,C,A,M" 
				datatype="string" parentElement="Tumor" sourceOfStandard="NAACCR13" />
			<ItemDef itemNo="280" itemName="IndCen" longName="Census Ind Code 1970-2000"
